### ISSUE TITLE
Failed to start component

### ISSUE THREAD

**Issue by llaumgui** [fjudith/docker-squash-tm#4]
Hi,

with a MySQL configuration, I have this trace:
```
 02-Feb-2018 15:03:06.360 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
  org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/squash-tm]]
         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
         at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:629)
         at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.NumberFormatException: null
         at java.lang.Long.parseLong(Long.java:552)
         at java.lang.Long.valueOf(Long.java:803)
         at org.squashtest.tm.web.internal.fileupload.SquashMultipartResolver.updateConfig(SquashMultipartResolver.java:63)
         at org.squashtest.tm.web.internal.fileupload.MultipartResolverDispatcher.onContextReady(MultipartResolverDispatcher.java:90)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:226)
         at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:143)
         at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:105)
         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
         at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:877)
         at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
         at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
         at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
         at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:150)
         at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:130)
         at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
         at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196)
         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
         ... 10 more

 02-Feb-2018 15:03:06.361 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying configuration descriptor [/usr/local/tomcat/conf/Catalina/localhost/squash-tm.xml]
  java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/squash-tm]]
         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
         at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:629)
         at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sandrine-Laure** [comment]
+1, any idea? @llaumgui did you find a fix?
